### ISSUE TITLE
Create Scoring

### ISSUE THREAD

**Issue by Major-Lag98** [Major-Lag98/Golf-N-Stuff#1]
Count the putts per level and display the correct term through UI after draining the ball.
Utilize the game sate machine to count putts.

Resources for scoring terms: https://golfbit.com/golf-scoring-terms

**Comment by Major-Lag98** [comment]
Depends on #2 to be completed.

**Comment by kendallcallison** [comment]
I created a branch with my progress on making the holes end the level. **Something within GameStateMachine.cs was not allowing the "Next Level" Button to work.** I did a rough fix of deactivating GameStateMachine in-between scene changes and it works though there must be a better solution.

**Comment by Major-Lag98** [comment]
@kendallcallison 
Please connect this to a branch.
Separate UI and Code. They both should be their own branch.
Changing levels should also be their own branch.
