### ISSUE TITLE
Expand testing level to incorporate draining.

### ISSUE THREAD

**Issue by Major-Lag98** [Major-Lag98/Golf-N-Stuff#2]
Utilize either ProBuilder or Blender to expand on the current testing level.
Level should now have a hole to sink the ball and count the score utilizing booleans.
Utilize unity colliders as a trigger to know when the ball is sunk.

Resources for ProBuilder boolean: https://docs.unity3d.com/Packages/com.unity.probuilder@4.0/manual/boolean.html

**Comment by kendallcallison** [comment]
I have a hole collider trigger that will allow for the player to go to the next hole

**Comment by Major-Lag98** [comment]
Please connect this issue to a branch
